export const ADD_COMMUNITY = 'ADD_COMMUNITY';
export const ADD_COMMUNITY_TO_REGION = 'ADD_COMMUNITY_TO_REGION';
export const MOVE_COMMUNITY = 'MOVE_COMMUNITY';
export const MUTATE_COMMUNITY = 'MUTATE_COMMUNITY';
export const CHANGE_POPULATION = 'INCREASE_POPULATION';
